

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_150 = Integer(150); _sage_const_61 = Integer(61); _sage_const_57 = Integer(57); _sage_const_55 = Integer(55); _sage_const_53 = Integer(53); _sage_const_51 = Integer(51); _sage_const_50 = Integer(50); _sage_const_47 = Integer(47); _sage_const_46 = Integer(46); _sage_const_45 = Integer(45); _sage_const_44 = Integer(44); _sage_const_43 = Integer(43); _sage_const_40 = Integer(40); _sage_const_34 = Integer(34); _sage_const_32 = Integer(32); _sage_const_31 = Integer(31); _sage_const_30 = Integer(30); _sage_const_28 = Integer(28); _sage_const_23 = Integer(23); _sage_const_21 = Integer(21); _sage_const_19 = Integer(19); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_89 = Integer(89); _sage_const_84 = Integer(84); _sage_const_82 = Integer(82); _sage_const_80 = Integer(80); _sage_const_77 = Integer(77); _sage_const_76 = Integer(76); _sage_const_75 = Integer(75); _sage_const_74 = Integer(74); _sage_const_68 = Integer(68); _sage_const_67 = Integer(67); _sage_const_66 = Integer(66); _sage_const_64 = Integer(64); _sage_const_63 = Integer(63); _sage_const_62 = Integer(62); _sage_const_52 = Integer(52); _sage_const_39 = Integer(39); _sage_const_38 = Integer(38); _sage_const_36 = Integer(36); _sage_const_33 = Integer(33); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_18 = Integer(18); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_14 = Integer(14); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0)
import hashlib
import json
from pathlib import Path

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

F = GF(_sage_const_2 )
R = PolynomialRing(F, names=('x',)); (x,) = R._first_ngens(1)
N = _sage_const_150 

f61 = x**_sage_const_61  + x**_sage_const_57  + x**_sage_const_55  + x**_sage_const_53  + x**_sage_const_51  + x**_sage_const_50  + x**_sage_const_47  + x**_sage_const_46  + x**_sage_const_45  + x**_sage_const_44  + x**_sage_const_43  + x**_sage_const_40  + x**_sage_const_34  + x**_sage_const_32  + x**_sage_const_31  + x**_sage_const_30  + x**_sage_const_28  + x**_sage_const_23  + x**_sage_const_21  + x**_sage_const_19  + x**_sage_const_13  + x**_sage_const_12  + x**_sage_const_11  + x**_sage_const_7  + x**_sage_const_4  + x**_sage_const_3  + x**_sage_const_2  + x + _sage_const_1 
f89 = x**_sage_const_89  + x**_sage_const_84  + x**_sage_const_82  + x**_sage_const_80  + x**_sage_const_77  + x**_sage_const_76  + x**_sage_const_75  + x**_sage_const_74  + x**_sage_const_68  + x**_sage_const_67  + x**_sage_const_66  + x**_sage_const_64  + x**_sage_const_63  + x**_sage_const_62  + x**_sage_const_57  + x**_sage_const_53  + x**_sage_const_52  + x**_sage_const_51  + x**_sage_const_50  + x**_sage_const_43  + x**_sage_const_40  + x**_sage_const_39  + x**_sage_const_38  + x**_sage_const_36  + x**_sage_const_34  + x**_sage_const_33  + x**_sage_const_32  + x**_sage_const_31  + x**_sage_const_27  + x**_sage_const_24  + x**_sage_const_18  + x**_sage_const_17  + x**_sage_const_16  + x**_sage_const_14  + x**_sage_const_13  + x**_sage_const_12  + x**_sage_const_10  + x**_sage_const_9  + x**_sage_const_8  + x**_sage_const_7  + x**_sage_const_4  + x**_sage_const_3  + _sage_const_1 
m = f61 * f89


def load_matrix(path):
    rows = [[int(c) for c in line.strip()] for line in Path(path).read_text().splitlines() if line.strip()]
    return matrix(F, rows)


def poly_from_vector(v):
    return sum(int(v[i]) * x**i for i in range(len(v)))


def eval_poly_on_matrix(poly, mat):
    out = zero_matrix(F, mat.nrows(), mat.ncols())
    for c in reversed(poly.list()):
        out = out * mat
        if c:
            out += identity_matrix(F, mat.nrows())
    return out


def field_elem(K, poly):
    poly = poly % K.modulus()
    return sum(int(c) * K.gen()**i for i, c in enumerate(poly.list()))


def lift_elem(elem):
    return sum(int(c) * x**i for i, c in enumerate(elem.polynomial().list()))


G = load_matrix("generator.txt")
A = load_matrix("alice.pub")
B = load_matrix("bob.pub")
enc = json.loads(Path("flag.enc").read_text())

e0 = vector(F, [_sage_const_1 ] + [_sage_const_0 ] * (N - _sage_const_1 ))
basis = []
cur = e0
for _ in range(N):
    basis.append(cur)
    cur = G * cur

K = matrix(F, N, N)
for j, v in enumerate(basis):
    K.set_column(j, v)

qa = poly_from_vector(K.solve_right(A.column(_sage_const_0 ))) % m
qb = poly_from_vector(K.solve_right(B.column(_sage_const_0 ))) % m

K61 = GF(_sage_const_2 **_sage_const_61 , modulus=f61, names=('a61',)); (a61,) = K61._first_ngens(1)
K89 = GF(_sage_const_2 **_sage_const_89 , modulus=f89, names=('a89',)); (a89,) = K89._first_ngens(1)

ga = K61.gen()
gb = K89.gen()

qa61 = field_elem(K61, qa)
qb61 = field_elem(K61, qb)
qa89 = field_elem(K89, qa)
qb89 = field_elem(K89, qb)

ord61 = _sage_const_2 **_sage_const_61  - _sage_const_1 
ord89 = _sage_const_2 **_sage_const_89  - _sage_const_1 

apriv61 = qa61.log(ga)
bpriv61 = qb61.log(ga)
apriv89 = qa89.log(gb)
bpriv89 = qb89.log(gb)

shared61 = ga**((apriv61 * bpriv61) % ord61)
shared89 = gb**((apriv89 * bpriv89) % ord89)

r61 = lift_elem(shared61)
r89 = lift_elem(shared89)
shared_poly = (r61 * f89 * inverse_mod(f89, f61) + r89 * f61 * inverse_mod(f61, f89)) % m
shared = eval_poly_on_matrix(shared_poly, G)

mat_str = "".join(str(int(x)) for row in shared.rows() for x in row)
key = hashlib.sha256(mat_str.encode()).digest()

decryptor = Cipher(algorithms.AES(key), modes.CBC(bytes.fromhex(enc["iv"]))).decryptor()
pt = decryptor.update(bytes.fromhex(enc["ciphertext"])) + decryptor.finalize()
print(pt[:-pt[-_sage_const_1 ]].decode())

